version: "3.8"
services:
  hrythym-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrythymdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend-app:
    build: .
    depends_on:
      - hrythym-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata:
